### PR TITLE
Normalize the unit in 'Sizes for all' row.

### PR DESCRIPTION
**Pull request by JinghongM**
Some bugs in my excel because of the OS language. Will keep testing in Linux OS.

### CODE REVIEW

**Comment by Xiaoxuhmm** [comment]
Hi, 
I really like your idea using replace to modify the unit.  And from my point of view,  would it be better if using a map in convertUnit function?   And I the loop processing data, I think maybe you can row instead of the column. I just get a little bit confused to see the column.  And from your algorithm, it seems you just used the last item in brandUnit[Brand], is that possible just record the last unit?

**Comment by JinghongM** [comment]
Actually, what I usually do with map function is change the type of a data, but in terms of string operation, I recommend using the string functions in python itself. 
Sorry, there is a typo of 'column', will correct it next version.
And about find the missing unit, I also thinking of finding the last unit in the same company. However, it may not so efficient for our algorithm, because it may cost too much time to search in dataframe row by row than search in the dictionary directly.

**Comment by Xiaoxuhmm** [comment]
Talking about the map, I think it's useful it we would like the apply the same function to different columns if  they have different units. 
And for find the missing unit, since you just used the recently used unit. I think if we define a variable recentUnit, to store the data, it would save the memory space.

**Comment by JinghongM** [comment]
Basically, X means a half, e.g. 6X means 6.5 years. 
Be care for excel may change the format of data automatically. 6-5 may be changed to 6/5/2017. So close the auto-correction function in excel.

**Comment by JinghongM** [comment]
ID converter added and size_convertor updated

**Pull request merged**
