### PR TITLE
Upload a file related to table design in db

### PR DESCRIPTION
**Pull request by Xiaoxuhmm**
Upload a file about Customers' use case, algorithm design, and tables in a database.

### CODE REVIEW

**Comment by Cody3123** [comment]
Awesome!

**Comment by Xiaoxuhmm** [comment]
Hey guys,

Well, a review can be a serious task, that means I would you guys could find out the problem in this commit. The problem can be a typo to some huge mistakes.  Please read the pull request and share what you guys think about this pull request.

**Comment by Cody3123** [comment]
I have some question:
1.do we need to specify the data type in our database(int or string)?
2.for some attribute in our table , its a range instead of an integer, does it matter?(when we need to extract the data for cloth recommendation engine?)
3.do we need to use the same unit for same attribute?(e.g. some brands use cm, some use inches

**Comment by Xiaoxuhmm** [comment]
@Cody3123 
For questions you mentioned above, Here are some answers.
1. Yes, We do need to specify the data type in our database.
2. The idea is we would like to keep the original size tag, such as inches, cm, Y, or anyway.  So we design a column to store the size in their tag, and another column to store a general size we used in our database as a searching key.
3. We try to keep all the original tags, so we would like to general height as the key, cause every clothes can have height or some attributes that can  change to height.

**Comment by JinghongM** [comment]
About 3rd question, for a single attribute, there will be only one unit.

**Comment by Xiaoxuhmm** [comment]
@Cody3123 @JinghongM @DustinZH 
If you guys have no question about this pull request, just leave an msg "LGTM". If all we agree to merge, someone could click approve to merge.

**Comment by Cody3123** [comment]
LGTM

**Comment by DustinZH** [comment]
LGTM

**Comment by JinghongM** [comment]
Although I didn't design a web app before, the algorithm looks good to me.

**Pull request merged**
